"""add user_settings table

Revision ID: 2c860eac220e
Revises: b542425d23b6
Create Date: 2026-03-22 13:48:48.798443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c860eac220e'
down_revision = 'b542425d23b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=256), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=256), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=256), nullable=True),
    sa.Column('recipient_email', sa.String(length=256), nullable=True),
    sa.Column('send_day', sa.Integer(), nullable=True),
    sa.Column('auto_send_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_send_date', sa.DateTime(), nullable=True),
    sa.Column('last_send_status', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
