"""add_organizations_table

Revision ID: e4f63c8b0c96
Revises: 2c860eac220e
Create Date: 2026-03-22 14:41:37.085826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f63c8b0c96'
down_revision = '2c860eac220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    organizations_table = op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed initial organizations
    op.bulk_insert(organizations_table, [
        {
            'id': 2596,
            'name': 'Kirchenkreis Dithmarschen',
            'token': 'd4ec66780546786c92b916f873ee713181c1b695d32e7ba9839e760eaecd3fa1',
            'description': 'Zentrale Verwaltung',
            'is_active': True,
        },
        {
            'id': 6572,
            'name': 'Kirchspiel Heide',
            'token': '7b0cf910b378c6d2482419f4e785fc95b18c1ec6fbfdd6dea48085b58f52e894',
            'description': 'Heide (St.-Jürgen, Erlöser, Auferstehung), Nordhastedt, Wesseln, Hemmingstedt, Eddelak',
            'is_active': True,
        },
        {
            'id': 2725,
            'name': 'Kirchspiel Eider',
            'token': '3afe57b4ae54ece02ff568993777028b47995601ecab92097e30a66f4d90494d',
            'description': 'Hennstedt, Lunden, Hemme, St. Annen, Schlichting, Weddingstedt, Ostrohe, Stelle-Wittenwurth',
            'is_active': True,
        },
        {
            'id': 2729,
            'name': 'Kirchspiel West',
            'token': 'bZq4GLCvhUbkYFQrDVDAe3cTs8hVlyQqEUmQ6xW5Tjw2EMEm3lCgYI6LSj3lrhvf7MTDIHL3TdrVXYdV',
            'description': 'Büsum, Neuenkirchen, Wesselburen, Urlauberseelsorge',
            'is_active': True,
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
