"""add_organizations_table

Revision ID: e4f63c8b0c96
Revises: 2c860eac220e
Create Date: 2026-03-22 14:41:37.085826

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = 'e4f63c8b0c96'
down_revision = '2c860eac220e'
branch_labels = None
depends_on = None


# (id, name, description) — Tokens kommen aus der Umgebung, nie aus dem Code.
# Erwartete Variable je Organisation: CHURCHDESK_ORG_<ID>_TOKEN
SEED = [
    (2596, 'Kirchenkreis Dithmarschen', 'Zentrale Verwaltung'),
    (6572, 'Kirchspiel Heide',
           'Heide (St.-Jürgen, Erlöser, Auferstehung), Nordhastedt, Wesseln, Hemmingstedt, Eddelak'),
    (2725, 'Kirchspiel Eider',
           'Hennstedt, Lunden, Hemme, St. Annen, Schlichting, Weddingstedt, Ostrohe, Stelle-Wittenwurth'),
    (2729, 'Kirchspiel West', 'Büsum, Neuenkirchen, Wesselburen, Urlauberseelsorge'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    organizations_table = op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed initial organizations — nur Orgs, deren Token in der Umgebung steht.
    # Ohne Token wird die Org uebersprungen statt mit leerem Token angelegt.
    to_insert = []
    for oid, name, desc in SEED:
        token = os.environ.get('CHURCHDESK_ORG_{}_TOKEN'.format(oid))
        if not token:
            continue
        to_insert.append({
            'id': oid,
            'name': name,
            'token': token,
            'description': desc,
            'is_active': True,
        })
    if to_insert:
        op.bulk_insert(organizations_table, to_insert)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
