version: '3.8'

services:
  gottesdienst-formatter:
    build: .
    container_name: gottesdienst-formatter
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - CHURCHDESK_API_TOKEN=${CHURCHDESK_API_TOKEN:-d4ec66780546786c92b916f873ee713181c1b695d32e7ba9839e760eaecd3fa1}
      - CHURCHDESK_ORGANIZATION_ID=${CHURCHDESK_ORGANIZATION_ID:-2596}